name: CICD

on: 
  workflow_dispatch: 
    inputs:
      environment:
        description: this is the env where the workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prd
          - staging
              
            
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: chechout code
        run: echo " code clone from github"

  test:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "code for test"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: build docker cont
        run: echo "docker cont build"

  deploy:
    needs: [build,test]
    if: inputs.environment == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: deploy the cont
        run: echo "code for deploy"
  
 
  
  
