name: Deploy To Server

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: docker-compose.yml
          target: ~/devops

      - name: SSH to Prod server and run app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "Running App"

            mkdir -p ~/devops

            sudo docker --version
            sudo docker compose version

            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login --username "${{ vars.DOCKERHUB_USER }}" --password-stdin

            cd ~/devops

            sudo DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }} DOCKER_TAG=latest docker compose down || true
            sudo DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }} DOCKER_TAG=latest docker compose up -d --force-recreate --pull always